Oops, DDP is still potato. Can not sync with SF.NET and local.
git-svn-id: svn://svn.debian.org/ddp/manuals/trunk@1700 313b444b-1b9f-4f58-a734-7bb04f332e8d

diff --git a/quick-reference/Makefile b/quick-reference/Makefile
--- a/quick-reference/Makefile
+++ b/quick-reference/Makefile
@@ -151,13 +151,13 @@ $(MANUAL).%.txt: $(MANUAL).%.sgml dynamic.%.ent $(SGMLSRCS)
 
 # PS
 
-$(MANUAL).%.ps: $(MANUAL).%.sgml dynamic.%.ent $(SGMLSRCS)
-	debiandoc2latexps -l $* $<
+#$(MANUAL).%.ps: $(MANUAL).%.sgml dynamic.%.ent $(SGMLSRCS)
+#	debiandoc2latexps -l $* $<
 
 # PDF
 
-$(MANUAL).%.pdf: $(MANUAL).%.sgml dynamic.%.ent $(SGMLSRCS)
-	debiandoc2latexpdf -l $* $<
+#$(MANUAL).%.pdf: $(MANUAL).%.sgml dynamic.%.ent $(SGMLSRCS)
+#	debiandoc2latexpdf -l $* $<
 
 # TAR
 
@@ -257,3 +257,68 @@ clean:
 .PHONY: all html text txt ps pdf files tar sf \
 	publish publish-all publish-html publish-files publish-tar \
 	clean distclean validate
+#########################################################################
+# maximum times we're willing to run TeX to get cross-references right, 
+# if you subtract by 3
+MAX_TEX_RECURSION	:= 6
+#----[ generating teTeX ]------------------------------------------------------
+$(MANUAL).%.tex: $(MANUAL).%.sgml dynamic.%.ent  $(SGMLSRCS)
+	debiandoc2latex -l $* $<
+
+#----[ generating PostScript ]-------------------------------------------------
+#$(MANUAL).%.ps: $(MANUAL).%.sgml date.ent dynamic.%.ent 
+#	debiandoc2latexps -l $* $<
+
+# debiandoc2latexps is broken. Imitate Makefile in boot-floppies
+$(MANUAL).%.ps:	$(MANUAL).%.tex dynamic.%.ent  $(SGMLSRCS)
+#	 note that I have seen bi-stable .aux files, thus we check two levels deep
+	@-cp -pf prior.aux pprior.aux 2>/dev/null
+	@-cp -pf $(basename $<).aux prior.aux 2>/dev/null
+#	 fail if we don't have pdflatex correctly installed
+	@kpsewhich latex.fmt >/dev/null
+#	 due to a bug in debiandoc2latex2e output, this might fail
+	@-latex '\nonstopmode\input{$<}' >/dev/null 
+	# see $(@:.ps=.log) for details
+	dvips -t `cat /etc/papersize` -o $(MANUAL).$*.ps $(MANUAL).$*
+	@set -e								;\
+	if ! cmp $(basename $<).aux prior.aux 2>/dev/null &&		\
+	   ! cmp $(basename $<).aux pprior.aux 2>/dev/null; then	\
+		if expr $(MAKELEVEL) '<' $(MAX_TEX_RECURSION) >/dev/null;\
+		then							\
+		   echo ">>> remaking $@ (take $(MAKELEVEL))"		;\
+		   rm -f $@						;\
+		   $(MAKE) $@						;\
+		else							\
+		   echo "E: $@ needs remaking, but we have reached max. level, $(MAX_TEX_RECURSION)" ;\
+		fi							\
+	fi
+	@rm -f prior.aux pprior.aux
+
+#----[ generating PDF ]--------------------------------------------------------
+# for translated languages
+#$(MANUAL).%.pdf: $(MANUAL).%.sgml date.ent dynamic.%.ent 
+#	debiandoc2latexpdf -l $* $<
+
+# debiandoc2latexpdf is broken. Imitate Makefile in boot-floppies
+$(MANUAL).%.pdf: $(MANUAL).%.tex dynamic.%.ent $(SGMLSRCS)
+#	 note that I have seen bi-stable .aux files, thus we check two levels deep
+	@-cp -pf prior.aux pprior.aux 2>/dev/null
+	@-cp -pf $(basename $<).aux prior.aux 2>/dev/null
+#	 fail if we don't have pdflatex correctly installed
+	@kpsewhich pdflatex.fmt >/dev/null
+#	 due to a bug in debiandoc2latex2e output, this might fail
+	@-pdflatex '\nonstopmode\input{$<}' >/dev/null 
+	# see $(@:.pdf=.log) for details
+	@set -e								;\
+	if ! cmp $(basename $<).aux prior.aux 2>/dev/null &&		\
+	   ! cmp $(basename $<).aux pprior.aux 2>/dev/null; then	\
+		if expr $(MAKELEVEL) '<' $(MAX_TEX_RECURSION) >/dev/null;\
+		then							\
+		   echo ">>> remaking $@ (take $(MAKELEVEL))"		;\
+		   rm -f $@						;\
+		   $(MAKE) $@						;\
+		else							\
+		   echo "E: $@ needs remaking, but we have reached max. level, $(MAX_TEX_RECURSION)" ;\
+		fi							\
+	fi
+	@rm -f prior.aux pprior.aux
