The publication of some manuals fails for some languages. Remove 'set -e' from the target so that this does not prevent other languages/arches from being copied over. This way we do not prevent the publication of languages that are fully ok
git-svn-id: svn://svn.debian.org/ddp/manuals/trunk@8446 313b444b-1b9f-4f58-a734-7bb04f332e8d

diff --git a/release-notes/Makefile b/release-notes/Makefile
--- a/release-notes/Makefile
+++ b/release-notes/Makefile
@@ -100,14 +100,15 @@ all: statistics.html
 	    done; \
 	done
 
-# TODO: if one of the files here is missing for one language due to a failed
-# build the publish will break the publish for the other languages. 
-# Make use of [ -e ] here ?
+# TODO: Do not use 'set -e' here. if one of the files here is missing for one
+# language due to a failed build the publish will break the publish for the
+# other languages. 
+# We could change this into a proper Makefile goal with its subtargets
+# but it needs to be rewritten to do so
 publish: statistics.html 
 	@test -n "$(PUBLISHDIR)" || { echo "ERROR: Variable PUBLISHDIR undefined" && false ; }
 	@test -d "$(PUBLISHDIR)" || { echo "ERROR: Publish dir '$(PUBLISHDIR)' does not exist" && false ; }
 	@echo "Publishing to '$(PUBLISHDIR)'"
-	set -ex; \
 	$(install_file) statistics.html $(PUBLISHDIR)/; \
 	echo "AddCharset UTF-8 .txt" > $(PUBLISHDIR)/.htaccess; \
 	for arch in $(arches); do \
